#!/usr/bin/env ruby

if File.exists?(File.join(File.expand_path('../..', __FILE__), '.gitignore'))
  ojs_path = File.expand_path('../../lib', __FILE__)
  $:.unshift(ojs_path)
end

require 'ojsubmitter/cli'
OJS::CLI.start
